### ISSUE TITLE
How to convert mobilenet model into tflite?

### ISSUE THREAD

**Issue by prajurock** [ibelem/aimark#1]

**Comment by ibelem** [comment]
Hi @prajurock thanks for the question, you can get the tflite format models directly from https://github.com/ibelem/aimark/blob/master/static/model/README.md 

What's your original model format of mobilenet?

**Comment by ibelem** [comment]
@prajurock BTW, i saw you are working on something with posenet, you can try: https://intel.github.io/webml-polyfill/examples/skeleton_detection/ This is the open source project that Intel is working on.

**Comment by prajurock** [comment]
yes I am working on deploy posenet tflite on mobile.


And I wanted to convert mobilenet 101 into tflite.

**Comment by ibelem** [comment]
@prajurock OK, seems like Google provided [075](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/multi_person_mobilenet_v1_075_float.tflite) rather than 101.  

Usually please use [TFLite convert cmdline](https://www.tensorflow.org/lite/convert/cmdline_examples) and [tflite_convert.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/tflite_convert.py) to convert models into tflite format. Do you have original 101 .pb file for posenet? Then you can convert the .pb file to .tflite.

If you have no any 101 .pb file, there may be another approach: Convert existed Tensorflow.js 101 model to tflite, maybe the [posenet-python project](https://github.com/rwightman/posenet-python) can do this but we didn't try.

**Posenet 101 tensorflow.js file**
https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_101/manifest.json

https://storage.googleapis.com/tfjs-models/weights/posenet/mobilenet_v1_101/
├── manifest.json
├── MobilenetV1_Conv2d_0_biases
├── MobilenetV1_Conv2d_0_weights
├── MobilenetV1_Conv2d_10_depthwise_biases
├── MobilenetV1_Conv2d_10_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_10_pointwise_biases
├── MobilenetV1_Conv2d_10_pointwise_weights
├── MobilenetV1_Conv2d_11_depthwise_biases
├── MobilenetV1_Conv2d_11_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_11_pointwise_biases
├── MobilenetV1_Conv2d_11_pointwise_weights
├── MobilenetV1_Conv2d_12_depthwise_biases
├── MobilenetV1_Conv2d_12_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_12_pointwise_biases
├── MobilenetV1_Conv2d_12_pointwise_weights
├── MobilenetV1_Conv2d_13_depthwise_biases
├── MobilenetV1_Conv2d_13_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_13_pointwise_biases
├── MobilenetV1_Conv2d_13_pointwise_weights
├── MobilenetV1_Conv2d_1_depthwise_biases
├── MobilenetV1_Conv2d_1_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_1_pointwise_biases
├── MobilenetV1_Conv2d_1_pointwise_weights
├── MobilenetV1_Conv2d_2_depthwise_biases
├── MobilenetV1_Conv2d_2_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_2_pointwise_biases
├── MobilenetV1_Conv2d_2_pointwise_weights
├── MobilenetV1_Conv2d_3_depthwise_biases
├── MobilenetV1_Conv2d_3_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_3_pointwise_biases
├── MobilenetV1_Conv2d_3_pointwise_weights
├── MobilenetV1_Conv2d_4_depthwise_biases
├── MobilenetV1_Conv2d_4_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_4_pointwise_biases
├── MobilenetV1_Conv2d_4_pointwise_weights
├── MobilenetV1_Conv2d_5_depthwise_biases
├── MobilenetV1_Conv2d_5_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_5_pointwise_biases
├── MobilenetV1_Conv2d_5_pointwise_weights
├── MobilenetV1_Conv2d_6_depthwise_biases
├── MobilenetV1_Conv2d_6_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_6_pointwise_biases
├── MobilenetV1_Conv2d_6_pointwise_weights
├── MobilenetV1_Conv2d_7_depthwise_biases
├── MobilenetV1_Conv2d_7_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_7_pointwise_biases
├── MobilenetV1_Conv2d_7_pointwise_weights
├── MobilenetV1_Conv2d_8_depthwise_biases
├── MobilenetV1_Conv2d_8_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_8_pointwise_biases
├── MobilenetV1_Conv2d_8_pointwise_weights
├── MobilenetV1_Conv2d_9_depthwise_biases
├── MobilenetV1_Conv2d_9_depthwise_depthwise_weights
├── MobilenetV1_Conv2d_9_pointwise_biases
├── MobilenetV1_Conv2d_9_pointwise_weights
├── MobilenetV1_displacement_bwd_2_biases
├── MobilenetV1_displacement_bwd_2_weights
├── MobilenetV1_displacement_fwd_2_biases
├── MobilenetV1_displacement_fwd_2_weights
├── MobilenetV1_heatmap_2_biases
├── MobilenetV1_heatmap_2_weights
├── MobilenetV1_offset_2_biases
└── MobilenetV1_offset_2_weights

**Comment by prajurock** [comment]
@ibelem ThankYou very much
